version: "3.9"
services:
  ldap:
    image: zokradonh/kopano_ldap_demo:latest
    hostname: kc-dev-ldap
    environment:
      LDAP_ORGANISATION: Kopano Dev
      LDAP_DOMAIN: kopano-dev.local
      LDAP_BASE_DN: dc=kopano-dev,dc=local
      LDAP_ADMIN_PASSWORD: kopano-dev
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_PASSWORD: kopano-dev
      LDAP_TLS: "false"

  db:
    image: mysql:5.7
    hostname: kc-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: kc-secret
      MYSQL_USER: kc-user
      MYSQL_PASSWORD: kc-secret
      MYSQL_DATABASE: kc_dev
    volumes:
      - "./mysql/kopano-dev.cnf:/etc/mysql/conf.d/kopano-dev.cnf:ro"

  kc:
    build:
      dockerfile: .github/docker/kc-test/Dockerfile
      context: ../../
      args:
        python_version: ${PYTHON_VERSION}
    ports:
      - "11236:11236"
    command: sh -c "sleep 20 && /app/core/core.sh"
    depends_on:
      - ldap
      - db
    deploy:
      restart_policy:
        condition: on-failure
