name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Lint check
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          make lint
      -
        name: Build and Run Kopanocore
        run: |
          PYTHON_VERSION=${{ matrix.python-version }} docker-compose -f .github/docker/docker-compose.yaml up -d
          while true; do docker-compose -f .github/docker/docker-compose.yaml ps kc && break || sleep 10; done
          sleep 60
      -
        name: Test Grapi
        run: |
          docker exec docker_kc_1 bash -c '/app/core/store.sh && cd /app/grapi/ && ./test.sh unit && ./test.sh integration'
      -
        name: Cleanup Stage
        run: |
          docker-compose -f .github/docker/docker-compose.yaml down --rmi all
